### ISSUE TITLE
One of several Radarr instances does not display Status

### ISSUE THREAD

**Issue by shaddowlink** [linuxserver/ifai#1135]
Hey,

This issue is for sure related, but I don't see any sultion of fix, was just closed:  https://github.com/linuxserver/Heimdall/issues/651

I have several radarr instances that I want to connect to heimdall.
They are all setup the same way and all work perfectly on all other apps that communicate with the API.
Only Poblem I have is that my main instance with the most content does not give back any Status in Heimdall, but the API check is successfull, just like with the other ones. 

![image](https://user-images.githubusercontent.com/4293045/226610882-b9fbc04e-c47a-4011-9a2e-a24b261ec585.png)
------------------
![image](https://user-images.githubusercontent.com/4293045/226611078-05e12263-e4de-4936-a013-a621ee407d5d.png)

Only difference is that this instance has the highest missing count / content, but sonarr has no trouble even with a big libary. All radarr instances run on the same version.
Tried completely starting from scratch 2 times now with no success. Same result main one does nothing, all other work.

**Comment by aptalca** [comment]
Most likely insufficient memory. If that radarr instance has a large library, that would do it.

The issue is, radarr api does not have a filter for missing items. So the api call returns the entire library info. With a large library, it's going to be a lot of data. When that data is large, php can exhaust the memory limit dedicated to each task and it will fail.

I hit the same issue (api response is 18MB, with the processing, it's multiplied).

I increased my php memory limit to 256MB and it's working again.

If you're using the lsio docker container, add `memory_limit = 256M` to `/config/php/php-local.ini`

**Comment by shaddowlink** [comment]
That did it, so it is a php issue not heimdall. Thx :)
