### ISSUE TITLE
Autofocus on address bar

### ISSUE THREAD

**Issue by Serhioromano** [linuxserver/ifai#1181]
When a new tab is opened and the search bar is switched off, is it possible to focus on the address bar of a tab? I am so used to it that when I start typing, it suggests sites or searches.

I think it is important issue because dashboard is about productivity. And when on one hand it makes it simplied for me to open some pages, I am still more often open new tabs for pages other that on my dashboard.

I configured it so that every new tab is opened with this dashboard in Edge. I used extension New Tab redirect for that, because there is no built in tools for Edge.

Is it possible somehow to keep the focus on browser address bar? Or at least make your search field so it searches through recently opened pages and search suggestions from Google.

**Comment by DavidFuchs** [comment]
Interesting, I've got the opposite problem, if I understand you correctly.

I'm using Edge, along with the [New Tab Changer](https://microsoftedge.microsoft.com/addons/detail/new-tab-changer/dlbnebcbaeajdpekcdhmcgdhoodcjpeg) extension. This extension navigates new tabs to a custom domain where I'm hosting Heimdall. If I click the '+' button to open a new tab in Edge, it opens Heimdall, and it always highlights the Edge address bar content. Previous to using Heimdall, this is exactly what I want.

When I enable the search bar in Heimdall, however, what I want is for it to auto-focus on that search bar, not on the Edge address bar. It does in fact auto-focus on Heimdall's search if I click a bookmark to open Heimdall, but not if I get there via the new tab redirect extension.

I've also tried with [Custom New Tab](https://microsoftedge.microsoft.com/addons/detail/custom-new-tab/onagfgjlokaciajhjmajljcfanonbmia). Same results.

**Comment by Serhioromano** [comment]
I've tried with search bar and without, same result for me, address bar never in focus.

**Comment by aptalca** [comment]
Not an expert but I believe the address bar focus would be controlled by the browser itself, and not the webpage displayed within.

The webpage _can_ control whether the focus is on the search bar within it (as part of its content) when opened. I understand you'd like the focus on there so you can type directly, however, that behavior is really undesirable on mobile because it forces the virtual keyboard to be opened, covering half the screen. I use Heimdall as a start page for the bookmarks/buttons, so the keyboard covering up half the bookmarks defeats that purpose.

Perhaps a user configurable setting in Heimdall would be a good option to put the focus on the search bar.
