### ISSUE TITLE
Public, read only, default user

### ISSUE THREAD

**Issue by titanbird** [linuxserver/ifai#1182]
I would like to offer anonymous users a default dashboard without any login needed containing links they can use but I don't want them to edit anything.
Is this possible? It's the only missing thing holding me back to use this wonderful peace of software!

**Comment by james-nicholson-std** [comment]
This would also be a useful feature for us. We are using heimdall to provide a menu into individual applications in our platform. It works great for our team, but we need an anonymous/read-only view we can share with our end users.

**Comment by FlowBowFPV** [comment]
We have the same problem. We whant to make a User static so that only the IT can change the URLs and not the Users

**Comment by xeviff** [comment]
Here another with this same desire. I have a public page I want to be the same for all users. What I have now, they are breaking it all the time....

**Comment by KodeStar** [comment]
This is already possible and has been since, well pretty much forever... Just allow public access to front and set a password. Then users can see the front page but not change anything.
<img width="346" alt="image" src="https://github.com/linuxserver/Heimdall/assets/5698566/b7554f78-15bb-4b70-920a-495051382a9e">
