### ISSUE TITLE
cant change the language

### ISSUE THREAD

**Issue by roswitina** [linuxserver/ifai#1243]
I use Heimdall 2.5.7.

I can't manage to switch to "German" under the settings. Only "english" is offered for selection. I helped myself by swapping the folder "en" with "de" in /resources/lang/. 

I know that this is not the intended way to change the language, but it helped me.

**Comment by juhacz** [comment]
I have the same issue. Heimdall installed as LXC container on Proxmox via Proxmox VE Helper Scripts(https://tteck.github.io/Proxmox/) ttps://tteck.github.io/Proxmox/

**Comment by MackBe** [comment]
Same issues for me. Did you find a solution ?

**Comment by xaimes** [comment]
https://github.com/tteck/Proxmox/issues/1695#issuecomment-1849836086

The problem has been solved. For it to work you would have to reinstall the script or clear the database (if u use Tteck scripts).

You could also use the workaround that is in the link.

The problem is the lack of php-intl when you first run the application (when db is created).

**Comment by fengqi** [comment]
i've solved, ths all of up
```
sudo apt-get install php-intl
php artisan db:seed
```

**Comment by MackBe** [comment]
Problem solved for me too. Thx everyone !

**Comment by geraldurbas** [comment]
> sudo apt-get install php-intl
> php artisan db:seed

it worked without problems

**Comment by geraldurbas** [comment]
Partly confirm: 
Solved by installing PHP intl Extension.
Database Initilalize was not necessary !
