### ISSUE TITLE
Icon must be a image

### ISSUE THREAD

**Issue by samotelf** [linuxserver/ifai#1244]
Hello.
Got this error when trying to set some applications.  
For instance gitea and grafana.  
You can see the icons missing here: https://apps.heimdall.site/
Thank you.

**Comment by chevyman142000** [comment]
I'm also getting this. In my case, I'm trying to add a connection for Pi-Hole.

**Comment by NicDoesIT** [comment]
Hi team,

Noticing the same issue to the point that it seems it might be impacting my Heimdall container when adding new apps to the dashboard.

The error message I receive is: "Icon must be an image.".

Example way I have replicated this issue is by:
1) selecting to add a new application
2) Select application type (In this test I selected pi-hole) which auto pulls an icon and pre-fills some details
3) Enter what ever relevant information remaining
4) Select Save

After selecting save the icon breaks, error message "Icon must be an image" appears and nothing was actually saved to the dashboard.

Checked the website: "https://apps.heimdall.site/search?search=pi-hole" and it appears the pi-hole icon is also broken there which would likely mean the root cause is pulling from the website and not the container itself.

Pi-Hole was not the only one seeing this issue and a few others like adding Portainer was seeing the same issue.

**Comment by Hekkfern** [comment]
Duplicated of  #1179

**Comment by JustEnoughDucks** [comment]
Also same issue with with Homeassistant icon, Heimdall version 2.5.8. 

Manually adding icons works. I suspect there is an error in pathing, so that it can find the image, but the path is wrong when trying to add it.

**Comment by KodeStar** [comment]
This should have been fixed. If you aren't seeing an image click on the `Update Apps List` button, some icons were updated to svg's and the list needs to be re-generated.
