### ISSUE TITLE
Link on https://apps.heimdall.site/request is wrong

### ISSUE THREAD

**Issue by andymarden** [linuxserver/ifai#1295]
It says "To get any of these apps follow this guide", but it takes you to:
```
https://github.com/linuxserver/Heimdall-Apps/wiki/Submitting-an-app
```
rather than:
```
https://github.com/linuxserver/Heimdall-Apps/wiki/Creating-Enhanced-Apps
```
Which has the instructions. Although the instructions need updating eg. where do you have to be to run php artisan?

**Comment by KodeStar** [comment]
The wording may be wrong, but the link isn't. We don't want people installing the apps like you are suggesting, that is for testing and creating enhanced apps. In order to get the apps into the app they need to follow the first guide, then when they are approved they will show up. We have literally 133 apps (the current requests) that could be added if someone added a pull request, but noone does, so they stay on the request list.
